### ISSUE TITLE
docker 版本 mapping volume 的問題

### ISSUE THREAD

**Issue by changchichung** [eyebluecn/tank#190]
我的docker-compose 如下
```
version: "3"
services:
   db:
     image: mysql:5.7
     volumes:
       - ./mysql:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: tank123
       MYSQL_DATABASE: tank
       MYSQL_USER: tank
       MYSQL_PASSWORD: tank123
   tank:
     image: eyeblue/tank:3.0.5
     depends_on:
       - db
     ports:
       - "6010:6010"
     restart: always
     environment:
       TANK_MYSQL_PORT: 3306
       TANK_MYSQL_HOST: db
       TANK_MYSQL_SCHEMA: tank
       TANK_MYSQL_USERNAME: tank
       TANK_MYSQL_PASSWORD: tank123
       TANK_ADMIN_USERNAME: admin
       TANK_ADMIN_EMAIL: admin@tank.eyeblue.cn
       TANK_ADMIN_PASSWORD: 123456
     volumes:
       - ./tank.json:/data/build/conf/tank.json
       - ./log:/data/log
       - ./matter:/data/matter
       #- ./data:/data

```
我想要在該目錄底下直接能夠看到所有人上傳的檔案
可是在docker 主機上面看 log / matter 目錄底下永遠都是空的

但是在容器裡面是可以找到我上傳的檔案的
請問該怎麼正確的設定 volume ?

我嘗試加入最後一行，去export 整個 /data 但是啟動時會出錯
```
ERROR: for tank_tank_1  Cannot start service tank: failed to create shim: OCI runtime create failed: runc create failed: unable to start container process: exec: "/data/build/tank": stat /data/build/tank: no such file or directory: unknown

ERROR: for tank  Cannot start service tank: failed to create shim: OCI runtime create failed: runc create failed: unable to start container process: exec: "/data/build/tank": stat /data/build/tank: no such file or directory: unknown
```
