### ISSUE TITLE
docker-compose support?

### ISSUE THREAD

**Issue by KISSMonX** [eyebluecn/tank#84]
1. i want docker-compose deploy.
2. disable mysql SSL Mode.

Any one help? 

```yaml
version: "3.7"

# Service
services:
  # Database MySQL
  MySQLDocker:
    image: mysql:8.0.19
    container_name: EyeBlueTankDB
    #restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: tank
      MYSQL_USER: tank
      MYSQL_PASSWORD: 123456
      MYSQL_OPT_SSL_MODE: SSL_MODE_DISABLED
    ports:
      - "3306:3306"
    networks:
      - app-server-network
  # Tank Server
  app-server:
    depends_on:
      - MySQLDocker
    image: eyeblue/tank:3.0.6
    volumes:
      - ./data/tank:/data/build/matter
    ports:
      - "6010:6010"
    networks:
      - app-server-network

# Network
networks:
  app-server-network:

```
